baseURL = 'https://zq.suns.bz/'
languageCode = 'en-us'
title = 'SUNS'

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[deployment]
[[deployment.targets]]
name = "production"
URL = "s3://suns-bz-content-690528115207?region=us-east-2&prefix=www/"

[[deployment.matchers]]
# Cache static assets with a cache-control header of 1 year
pattern = "^.+\\.(js|css|svg|ttf|woff|woff2|png|jpg|jpeg|gif|ico)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
# Cache HTML files with a cache-control header of 5 minutes
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "max-age=300, no-transform, public"
gzip = true
